on:
  #schedule:
  #- cron: 0 6 * * 1
  workflow_dispatch:
name: Update Dependencies
jobs:
  package-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: set remote url
      run: git remote set-url --push origin https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
    - name: Checkout GitHub Action Repo
      uses: actions/checkout@v2
      with:
        repository: elestu/actions-dependacop
        ref: v0.0.1
        token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
        path: .github/actions/actions-dependacop
    - name: Run My Action
      uses: ./.github/actions/actions-dependacop
      env:
        AUTHOR_EMAIL: hello@loopstudio.dev
        AUTHOR_NAME: Loopito
        EXECUTE: "true"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        COMMIT_MESSAGE: Update Dependencies
        LOG_LEVEL: debug
        UPDATE_COMMAND: yarn
      with:
        args: upgrade --latest
